apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: frontend
 namespace: frontend
spec:
  selector:
    matchLabels:
      app: whereami-frontend
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
          - asm-ingress
        principals: [ "csm001.svc.id.goog/ns/asm-ingress/sa/asm-ingressgateway" ]
#  - to:
#    - operation:
#        methods: ["GET"]