nameSuffix: "-backend"
namespace: backend
commonLabels:
  app: whereami-backend
  version: v1
resources:
- ../base
patches:
- path: cm-flag.yaml
  target:
    kind: ConfigMap
- path: service-type.yaml
  target:
    kind: Service
- path: ksa-annotation.yaml
  target:
    kind: ServiceAccount
